name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read

jobs:
  draft_release:
    name: Draft Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📝 Draft Release
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
