name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read

jobs:
  draft_release:
    permissions:
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: 📝 Draft Release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}