name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 🏷️ Bump manifest version
        run: python scripts/bump_version ${{ github.ref_name }}

      - name: 📦 Create zip package
        working-directory: custom_components/check_weather
        run: zip -r check-weather.zip .

      - name: 📤  Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: custom_components/check_weather/check-weather.zip
          asset_name: check-weather.zip
          tag: ${{ github.ref }}
          overwrite: true